# Generated by Django 2.2.5 on 2019-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('timestamp', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=300)),
                ('content', models.TextField(default='This post has no content yet.')),
                ('author', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_image', models.ImageField(upload_to='')),
                ('post_image_alt', models.CharField(default='post_image_alt', max_length=50)),
                ('post_cover', models.ImageField(upload_to='')),
                ('post_cover_alt', models.CharField(default='post_cover_alt', max_length=50)),
                ('tags', models.CharField(default="Tags'n'stuff", max_length=50)),
            ],
        ),
    ]
